### ISSUE TITLE
Состояние моторов

### ISSUE THREAD

**Issue by plotter241854641534645** [GyverLibs/GyverMotor#1]
Можно ли добавить возможность опрашивать состояние моторов по текущему состоянию крутится/стоит?

**Comment by GyverLibs** [comment]
Именно моторов, или сигнала библиотеки?

**Comment by plotter241854641534645** [comment]
Состояние в библиотеке конечно. В ситуации когда нужно рулить несколькими моторами от источника который может вытянуть одновременно только один моторчик. В принципе сейчас обхожусь флагами, но когда моторов много, то и флагов становится не мало...

**Comment by GyverLibs** [comment]
Такое есть
int getState();
// возвращает -1 при вращении BACKWARD, 1 при FORWARD и 0 при остановке и торможении

**Comment by GyverLibs** [comment]
Такое есть
int getState();
// возвращает -1 при вращении BACKWARD, 1 при FORWARD и 0 при остановке и торможении

**Comment by plotter241854641534645** [comment]
О, супер! 
А в документации об этом ни слова :)

**Comment by GyverLibs** [comment]
Чорт! Я не знаю как так вышло, документация обычно просто копируется из файла библиотеки. Поправлю сегодня, спасибо
