### ISSUE TITLE
Бага/неправильное использование с setMode

### ISSUE THREAD

**Issue by BubonicPestilence** [GyverLibs/GyverMotor#3]
Это не столько бага, сколько возможность неправильного использования.

есть функция tick_motor
она включает/выключает движок и меняет направление.
использую режим AUTO

Но тут возникает вопрос, как поставить на тормоз/остановить?

По началу юзал:

```
function tick_motor() {
    if (distance_to_move == 0) {
        setMode(STOP);
    } else {
        setMode(AUTO);
        setSpeed(...);
    }
}
```

во время старта/стопа всё ок, но во время последующих тиков во время движения, из-за setMode(AUTO) шим сначала вырубался, а потом врубался (ибо `setMode(AUTO)` вызывает `setPin/сбрасывает`, а потом `setSpeed` устанавливает на переданные значения). Что-то вроде Deadtime между тиками.

Сначала решил с помощью `if (!getState()) setMode(AUTO);`, потом понял, что надо `setSpeed(0);`
Но как тогда поставить на тормоз? (не используя run())

Я понимаю что плохо читал доку. Но если сделать проверку `if (_mode == mode) { return }` внутри `setMode`, проблемы не было бы :)

**Comment by GyverLibs** [comment]
Сейчас работаю над новой версией, она будет сильно удобнее в использовании. Текущая реализация сделана по образу и подобию другой популярной мотор либы, но сейчас понимаю что это хлам)

**Comment by GyverLibs** [comment]
добавил строчку в релиз, спасибо! Также вышла версия GyverMotor2, она лучше оптимизирована и более удобна в управлении
