### ISSUE TITLE
esp32 compilation error with accelmotor lib

### ISSUE THREAD

**Issue by iqubik** [GyverLibs/GyverMotor#5]
Обновил до последней версии GyverMotor ошибка компиляции скетча не прошла. Та же ошибка под esp32
![image](https://github.com/GyverLibs/GyverMotor/assets/22661808/b6b3b015-d2cd-4ad7-af39-42a16a89b4e5)

**Comment by GyverLibs** [comment]
Привет, естественно, ядро esp32 не является полноценно ардуино совместимым. Вон написано же - нет функции analogwrite
