### ISSUE TITLE
Режим для H моста с синфазными ключами

### ISSUE THREAD

**Issue by waw555** [GyverLibs/GyverMotor#6]
Здравствуйте, Александр!

Просьба добавить режим работы для H моста с синфазными ключами.

**Comment by GyverLibs** [comment]
Здравствуйте, а можно на пальцах что требуется от пинов и шимов?

**Comment by waw555** [comment]
Не могу точно это описать как это должно быть, но работает это примерно так:

При противофазном управлении, при подаче логической единицы на оба пина (Например D2 и PWM D3 у Arduino Nano), мы получим активное торможение.

При синфазном управлении, при подаче логической единицы на оба пина (Например D2 и PWM D3 у Arduino Nano), мы получим короткое замыкание.

Сейчас используя пример serialControl.ino, я могу вращать двигатель только в одном направлении, я использую пин D2 и PWM D3, отправляя в порт команду q со скоростью, я получаю нормально работающий двигатель, при использовании e (brake) я получаю короткое замыкание. При синфазном управлении, нельзя использовать торможение.

**Comment by GyverLibs** [comment]
Ну так не нужно использовать brake, если нельзя)

**Comment by waw555** [comment]
Реверс в данном случае, так же не работает. Если крутить мотор в прямом направлении, то все отлично, если в обратном, то ток потребления уходит в космос, двигатель еле крутит и ключи греются. Если поменять местами D2 и D3, то все аналогично, только в другую сторону.

**Comment by GyverLibs** [comment]
Поэтому я и спросил в первом сообщении, какие пины/шимы нужны такому драйверу

**Comment by waw555** [comment]
Погуглив, пришел к следующему  выводу:

1. Нужно использовать оба пина с PWM, в прямом направление 1 пин как обычный пин, а второй пин как PWM, в режиме реверса 1 пин с pwm, а 2 пин как обычный пин.
2. Нужна задержка между подачей сигнала на пины, то есть, нельзя синхронно подавать сигнал на пины при переходе из прямого направления в реверс, нужна минимальная задержка.

**Comment by waw555** [comment]
Вот такая конструкция работает без проблем

```
void setup() {
  // put your setup code here, to run once:
  pinMode(5, OUTPUT);
  pinMode(6, OUTPUT);

}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(6, LOW);
  delay(5);
  analogWrite(5, 100);
  delay(5000);
  analogWrite(5, 0);
  delay(1000);
  digitalWrite(5, LOW);
  delay(5);
  analogWrite(6, 100);
  delay(5000);
  analogWrite(6, 0);
  delay(1000);
}
```

**Comment by GyverLibs** [comment]
1. В gmotor2 есть тип `DRIVER2WIRE_PWM`, работает именно так
2. `void setDeadtime();   // установить deadtime в микросекундах (умолч. 0)`
